laravel_lms_demo/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/ajex', function () {
    return view('ajexlaravel/profile');
});


//Route::view('ajex','profile');
//Route::get('/ajex', function () {
//    return view('author');
//});


Route::resource('/author','AuthorController');
Route::resource('/book','BookController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/active-deactive','AuthorController@Confirm');
Route::post('/active-deactive1','BookController@Confirm_');
//Route::get('/updateBookStatus/{id}','BookController@updateBookStatus');

laravel_lms_demo/resources/views/author.blade.php
@extends('layouts.app')
@section('js')
    <script src="{{asset('assets/js/plugins/table/datatables/datatables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/plugins/forms/datatables/selects/select2.min.js')}}"
            type="text/javascript"></script>
    <script src="{{asset('assets/js/demo_pages/datatables_advanced.js')}}" type="text/javascript"></script>
@endsection
@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card  bg-primary">
                    <h3 class="mx-auto my-auto text-white text-uppercase">Author Data</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="card">
                <div class="card-title">
                </div>
                <div class="card-body">
                    <div class="card">
                        <div class="card-header header-elements-inline">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <button class="btn btn-primary "><a href="{{ route('author.create') }}" class="text-white">Fill
                                    Author Data</a></button>
                        </div>

                        <table class="table bg-primary datatable-dom-position">
                            <thead>
                            <tr>
                                <th>Full Name</th>
                                <th>Dob</th>
                                <th>Gender</th>
                                <th>Address</th>
                                <th>Mobile_no</th>
                                <th class="text-center">Description</th>
                                {{--                            <th class="text-center">Status</th>--}}
                                <th scope="col">Status</th>

                                <th scope="col">
                                    Activity
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($author as $as)
                                <tr>
                                    <th scope="row">{{$as->fullname}}</th>
                                    <td>{{$as->dob}}</td>
                                    <td>{{$as->gender}}</td>
                                    <td>{{$as->address_ }}</td>
                                    <td>{{$as->mobile_no}}</td>
                                    <td>{{$as->description_}}</td>
                                    <td>{{$as->status}}</td>
                                    <td><a class="btn btn-success" href="{{ route('author.edit',$as->id) }}"><span class="text-uppercase">Edit</span></a>
                                    </td>
                                    <td>
                                        <form action="{{ route('author.destroy',$as->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger text-uppercase ">Delete</button>
                                        </form>
                                    </td>
                                    <td>
                                        <button class="btn btn-dark text-uppercase"><a
                                                href="{{route('author.show',$as->id)}}"><span class="text-white">Show</span></a></button>
                                    </td>
                                    <td>
                                        <form action="/active-deactive" method="POST">
                                            @csrf
                                            <div class="input-group">
                                                <input type="hidden" class="form-control" name="v" value="{{$as->id}}">
                                                <select required class="form-control" id="status" name="status">
                                                    <option value="1">Active</option>
                                                    <option value="0">De-Active</option>
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-primary">
                                                <span>Confirm</span>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel_lms_demo/resources/views/authorcreate.blade.php
@extends('layouts.app')
@section('js')
    {{--    <script src="{{ url('js/app.js') }}"></script>--}}
    <script src="{{asset('assets/js/plugins/radio/checkboxes_radios.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/styling/uniform.min.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/styling/switchery.min.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/styling/switch.min.js')}}" type="text/javascript"></script>

    <script src="{{url('assets/js/plugins/forms/inputs/inputmask.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/inputs/maxlength.min.js')}}" type="text/javascript"></script>
        <script src="{{url('assets/js/demo_pages/form_inputs.js')}}" type="text/javascript"></script>
         <script src="{{url('assets/js/plugins/forms/inputs/formatter.min.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/demo_pages/form_controls_extended.js')}}" type="text/javascript"></script>
@endsection

@section('content')
    <div class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('author.store') }}" method="POST" id="myform" name="form">
            @csrf
            <div class="form-group row">
                <label class="col-form-label col-lg-2">Full name</label>
                <div class="col-lg-10">
                    <input type="text" name="fullname" id="firstname"
                           class="form-control aa  text-violet  bg-primary border-info-600 border-1" id="firstname"
                           aria-describedby="emailHelp" placeholder="Enter your username...">
                    <span class="text-danger">  @error('fullname')
                        {{$message}}
                        @enderror
                    </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Date</label>
                <div class="col-md-10">
                    <input type="date" class="form-control bg-primary border-info-600 border-1" name="dob" id="dob"
                           placeholder="Date-of-Birth">
                    <span class="text-danger">  @error('dob')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Select Gender</label>
                <div class="col-md-10">
                    <div class="form-check form-check-inline">
                        <label class="form-check-label">
                            <input type="radio" class="form-check-input-styled" name="gender" value="male" checked
                                   data-fouc>
                            Male
                        </label>
                    </div>
                    <div class="form-check form-check-inline">
                        <label class="form-check-label">
                            <input type="radio" class="form-check-input-styled" name="gender" value="female" data-fouc>
                            Female
                        </label>
                    </div>
                    <div class="form-check form-check-inline">
                        <label class="form-check-label">
                            <input type="radio" class="form-check-input-styled" name="gender" value="other" data-fouc>
                            Other
                        </label>
                    </div>
                    <span class="text-danger">  @error('gender')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-form-label col-md-2">Address</label>
                <div class="col-md-10">
                    <input type="text" class="form-control bg-primary border-info-600 border-1" id="desc1"
                           name="address_" placeholder="Enter your Address">
                    <span class="text-danger">  @error('address_')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-form-label col-md-2 ">Mobile Number</label>
                <div class="col-md-10">
                    <input type="text" class="form-control format-phone-number bg-primary border-info-600 border-1" id="m_number"
                           name="mobile_no"
                           placeholder="Enter Mobile Number">
                    <span class="text-danger">  @error('mobile_no')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-lg-2">Description</label>
                <div class="col-lg-10">
                    <textarea rows="4" cols="50" id="desc" name="description_">
                            data is not avalable
                    </textarea>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-lg-2"></label>
                <div class="col-lg-10">
                    <button type="submit" class="btn btn-primary" name="submit" id="submit">Submit</button>
                </div>
            </div>


        </form>
    </div>
@endsection

laravel_lms_demo/resources/views/authoredit.blade.php
@extends('layouts.app')
@section('js')
    <script src="{{asset('assets/js/plugins/radio/checkboxes_radios.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/styling/uniform.min.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/styling/switchery.min.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/styling/switch.min.js')}}" type="text/javascript"></script>
    {{--    <script src="{{ url('js/app.js') }}"></script>--}}

    <script src="{{url('assets/js/plugins/forms/inputs/inputmask.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/inputs/maxlength.min.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/demo_pages/form_inputs.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/inputs/formatter.min.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/demo_pages/form_controls_extended.js')}}" type="text/javascript"></script>
@endsection
@section('content')
    <div class="container">

        <form action="{{ route('author.update',$author->id) }}" method="POST" id="myform" name="form">

            @method('PUT')
            @csrf

            <div class="form-group row">
                <label class="col-form-label col-lg-2">Full name</label>
                <div class="col-lg-10">
                    <input type="text" name="fullname" id="firstname"
                           class="form-control aa  text-violet  bg-primary border-info-600 border-1"  value="{{$author->fullname}}" id="firstname"
                           aria-describedby="emailHelp" >
                    <span class="text-danger">  @error('fullname')
                        {{$message}}
                        @enderror
                    </span>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-form-label col-md-2">Date</label>
                <div class="col-md-10">
                    <input type="date" class="form-control bg-primary border-info-600 border-1" name="dob" id="dob"
                           value="{{$author->dob}}">
                    <span class="text-danger">  @error('dob')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-form-label col-md-2">Select Gender</label>
                <div class="col-md-10">
                    <div class="form-check form-check-inline">
                        <label class="form-check-label">
                            <input type="radio" class="form-check-input-styled" name="gender" value="male" checked
                                   data-fouc>
                            Male
                        </label>
                    </div>
                    <div class="form-check form-check-inline">
                        <label class="form-check-label">
                            <input type="radio" class="form-check-input-styled" name="gender" value="female" data-fouc>
                            Female
                        </label>
                    </div>
                    <div class="form-check form-check-inline">
                        <label class="form-check-label">
                            <input type="radio" class="form-check-input-styled" name="gender" value="other" data-fouc>
                            Other
                        </label>
                    </div>
                    <span class="text-danger">  @error('gender')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Address</label>
                <div class="col-md-10">
                    <input type="text" class="form-control bg-primary border-info-600 border-1" value="{{$author->address_}}" id="desc1"
                           name="address_" placeholder="Enter your Address">
                    <span class="text-danger">  @error('address_')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2 ">Mobile Number</label>
                <div class="col-md-10">
                    <input type="text"  value="{{$author->mobile_no}}" class="form-control format-phone-number bg-primary border-info-600 border-1" id="m_number"
                           name="mobile_no"
                           placeholder="Enter Mobile Number">
                    <span class="text-danger">  @error('mobile_no')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>



            <div class="form-group row">
                <label class="col-form-label col-lg-2">Description</label>
                <div class="col-lg-10">
                    <textarea rows="4" cols="50" id="desc" name="description_">
                            {{$author->description_}}
                    </textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label col-lg-2"></label>
                <div class="col-lg-10">
                    <button type="submit" class="btn btn-primary" name="submit" id="submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
@endsection

laravel_lms_demo/resources/views/book.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card  bg-primary">
                    <h3 class="mx-auto my-auto text-white text-uppercase">Book Data</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="col-md-12">
            <div class="card">
                <div class="card-title">
                </div>
                <div class="card-body">
                    <div class="card">
                        <div class="card-header header-elements-inline">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <button class="btn btn-primary "><a href="{{ route('book.create') }}" class="text-white text-uppercase">Fill book Data</a></button>
                        </div>
                        <table class="table bg-primary datatable-dom-position">
                            <thead>
                            <tr class="text-dark text-uppercase">
                                <th>Author Id</th>
                                <th>Title</th>
                                <th>Pages</th>
                                <th>Langauge</th>
                                <th>Cover_image</th>
                                <th class="text-center">Isbn</th>
                                <th scope="col">Status</th>
                                <th scope="col">Activity</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($book as $bk)
                                <tr>
                                    <th scope="row">{{$bk->author_id}}</th>
                                    <th scope="row">{{$bk->title}}</th>
                                    <td>{{$bk->pages}}</td>
                                    <td>{{$bk->langauge}}</td>
                                    <td>{{$bk->cover_image }}</td>
                                    <td>{{$bk->isbn}}</td>
                                    <td>{{$bk->status}}</td>
                                    <td><a class="btn btn-success" href="{{ route('book.edit',$bk->id)}}"><span class="text-white text-uppercase">Edit</span></a></td>
                                    <td>
                                        <form action="{{ route('book.destroy',$bk->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-danger text-uppercase text-white">Delete</button>
                                        </form>

                                    </td>
                                    <td><button class="btn btn-dark text-uppercase  "><a href="{{route('book.show',$bk->id)}}"><span class="text-white">Show</span></a></button></td>

                                    <td>

                                        <form action="/active-deactive1" method="POST">
                                            @csrf
                                            <div class="input-group">
                                                <input type="hidden" class="form-control" name="v" value="{{$bk->id}}">
                                                <select required class="form-control" id="status"  name="status">
                                                    <option value="1" class="">Active</option>
                                                    <option value="0">De-Active</option>
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-outline-secondary">
                                                <span class="text-white">Confirm</span>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel_lms_demo/resources/views/bookcreate.blade.php
@extends('layouts.app')
@section('js')
    <script src="{{url('assets/js/plugins/forms/styling/uniform.min.js')}}" type="text/javascript"></script>
    {{--        <script src="{{ url('js/app.js') }}"></script>--}}
    <script src="{{url('assets/js/plugins/forms/inputs/inputmask.js')}}" type="text/javascript"></script>
    <script src="{{url('assets/js/plugins/forms/inputs/maxlength.min.js')}}" type="text/javascript"></script>
{{--    <script src="{{url('assets/js/demo_pages/form_inputs.js')}}" type="text/javascript"></script>--}}
{{--    <script src="{{url('assets/js/plugins/forms/inputs/autosize.min.js')}}" type="text/javascript"></script>--}}
{{--    <script src="{{url('assets/js/plugins/forms/inputs/formatter.min.js')}}" type="text/javascript"></script>--}}
{{--    <script src="{{url('assets/js/plugins/forms/inputs/passy.js')}}" type="text/javascript"></script>--}}
{{--    <script src="{{url('assets/js/plugins/forms/inputs/typeahead/handlebars.min.js')}}" type="text/javascript"></script>--}}
{{--    <script src="{{url('assets/js/plugins/forms/inputs/typeahead/typeahead.bundle.min.js')}}" type="text/javascript"></script>--}}

@endsection
@section('content')
    <div class="container">

        <form action="{{ route('book.store') }}" method="POST" id="myform" name="form" enctype="multipart/form-data">
            @csrf

            <div class="form-group row">
                <label class="col-form-label col-lg-2">Book Author</label>
                <div class="col-lg-10">
                    <select class="custom-select bg-primary @error('book_author') is-invalid @enderror" name="author_id"
                            id="author_id">
                        <option hidden value="">Book Author</option>
                        @foreach($author as $author)
                            <option value="{{ $author->id }}">{{ $author->fullname}}</option>
                        @endforeach
                    </select>
                    <span class="text-danger">
                @error('author_id')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-lg-2">Title</label>
                <div class="col-lg-10">
                    <input type="text" name="title" id="title" class="form-control bg-primary" aria-describedby="emailHelp"
                           placeholder="Enter Book Title">
                    <span class="text-danger">
                @error('title')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Pages</label>
                <div class="col-md-10">
                    <input type="number" name="pages" id="pages" class="form-control bg-primary" id="lastname"
                           aria-describedby="emailHelp" placeholder="Enter Pages">
                    <span class="text-danger">
                        @error('pages')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-form-label col-lg-2">langauge</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control bg-primary" name="langauge" id="langauge" placeholder="Enter Book Langauge">
                    <span class="text-danger">
                @error('langauge')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-lg-2">Cover Image</label>
                <div class="col-lg-10">
                    <input type="file" class="form-control-uniform-custom" id="image" name="cover_image" placeholder="Enter Cover Image">
                    <span class="text-danger">
                @error('cover_image')
                        {{$message}}
                        @enderror
                </span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-lg-2">ISBN Number</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control bg-primary" name="isbn" id="isbn"  data-mask="999-99-999-9999-9" placeholder="Isbn Number">
                    <span class="form-text text-muted">999-99-999-9999-9</span>
                    <span class="text-danger">@error('isbn'){{$message}}@enderror</span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-lg-2">Description</label>
                <div class="col-lg-10">
                  <textarea rows="4" cols="50" id="desc" name="description" placeholder="Description">
                 </textarea>
                    <span class="text-danger">@error('description'){{$message}}@enderror</span>

                </div>
            </div>
            <button type="submit" class="btn btn-primary" name="submit" id="submit">Submit</button>

        </form>
    </div>
@endsection

laravel_lms_demo/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                        <h1> {{$user->name}} is  successfull loging! </h1>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel_lms_demo/resources/views/showbook.blade.php
@extends('layouts.app')
@section('content')
    <table class="table table-striped table-hover table-dark">
        <thead>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="card">
                <div class="card-title">
                </div>
                <div class="card-body">
                    <div class="card">
                        <div class="card-header header-elements-inline">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <button class="btn btn-primary "><a href="{{ route('book.create') }}" class="text-white text-uppercase">Fill book Data</a></button>
                        </div>
                            <table class="table bg-primary datatable-dom-position">
                            <thead>
                            <tr class="text-uppercase text-dark">
                                <th scope="col">Title</th>
                                <th scope="col">pages</th>
                                <th scope="col">langauge</th>
                                <th scope="col">cover_image</th>
                                <th scope="col">isbn</th>
                                <th scope="col">description</th>
                                <th scope="col">status</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Updated At</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{$book->title}}</td>
                                <td>{{$book->pages}}</td>
                                <td>{{$book->langauge }}</td>
                                <td><img src="{{$book->cover_image  }}" height="100px" width="100px"></td>
                                <td>{{$book->isbn}}</td>
                                <td>{{$book->description}}</td>
                                <td>{{$book->status}}</td>
                                <td>{{$book->created_at}}</td>
                                <td>{{$book->updated_at}}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection